language: cpp

matrix:
    include:
        - name: "Linux, Debug"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
              - Qt5_DIR="/opt/qt512/lib/cmake/Qt5"
        - name: "Linux, Release"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
              - Qt5_DIR="/opt/qt512/lib/cmake/Qt5"
        - name: "macOS, Debug"
          os: osx
          osx_image: xcode10.2
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"
        - name: "macOS, Release"
          os: osx
          osx_image: xcode10.2
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
            - libgl1-mesa-dev
            - qt512-meta-full
            - unzip
            - wget
            - rpm
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt-5.12.3-xenial"
    homebrew: # macOS
        packages:
            - cmake
            - git
            - qt5

cache:
    directories:
        - $HOME/.hunter

script:
    - mkdir ./build && cd ./build
    - >
        cmake -G "$CMAKE_GENERATOR_NAME"
        -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
        -DCMAKE_TOOLCHAIN_FILE=cmake/polly/$CMAKE_TOOLCHAIN_FILE_NAME
        -DBUILD_ALL:BOOL=TRUE
        ..
    - cmake --build . --config $CMAKE_BUILD_TYPE -- -j 2
    - cpack -C $CMAKE_BUILD_TYPE

deploy:
    provider: releases # GitHub Releases
    api_key:
        secure: "Rg5gMy0QszJp0IwBex0KQCcOdjHQyzJOq0ff8zS8Ep4svfGnr9M5ggYbABTCQV1NYI0fmmIQQwno1d2EZhYgBH7cLJuyWunyU6bxMTBfxLJ0buc8+4XLNE/b5D5A8uv3cCxod+vfBGnCtihr1CdszOTvpi6WmxnP6Aj6eF6kLLTLzqNvU0Ug0/LDR29NQ8+2rc6Y+qEilVXJfiO1zZXZgzObeQJA5Pdn/cWdYWnE/fzlUk0nH2G9R/6siDAL30hUx/sGRcsBJCY18OAi7hYq2vdVZLw8JjMu9pj7Vrl4Eq5WQXUUKFoZlzIkI7HcYI9BjOx6Hg30op3B1RMmvUAq8YG1u+KIuidbwiHHwdvuPr9br95RPpi7k4sFXhd7NHUwAe9Z87hIxJ6xxP2ym17KN5oOG1PPnAPWm58PEVDfZ876HlYTa8ZUSaI7TMxtvVaSTFyINgPGnoFpWCE+17RGQ8+q+zY/98AVXrvQ1oniLHtEnnMDs3SlNOPT+viG6xourZ8sD/SQ7EiACe0BxpmQrjlnZhHSTwuWUBK4/fNi6Wc4mkcLFdi634Tj/VCZGHVQW2aGbkgJL5OwUF/QWnTQdULwt5s7V5W8B4HynbP6+lBmdMSPIrOJ1dONO1XdrGoQiNtCppxsWXcB1Zz4ui8j4E6WImjsqL1TbmV3jPe3tQw="
    file: dist/qwertycoin-zero-* # path is relative to the current working directory, not to $TRAVIS_BUILD_DIR
    file_glob: true
    draft: true
    on:
        branch: master
        tags: true
        condition: $CMAKE_BUILD_TYPE = "Release"
    skip_cleanup: true
